language: csharp
solution: aivolution.sln
mono:
  - latest
script:
  - xbuild /p:Configuration=Release aivolution.sln
  - mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./aibio.Tests/bin/Release/aibio.Tests.dll
  - mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./aibio.Tests/bin/Release/ainet.Tests.dll